
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ecommerce_data_engineering'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'ecommerce_data_engineering'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ log('Starting ecommerce_data_engineering run', info=True) }}"
on-run-end:
  - "{{ log('Finished ecommerce_data_engineering run', info=True) }}"

vars:
  project_schema: "ecommerce_data_engineering"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  ecommerce_data_engineering:
    staging:
      +materialized: view
      +schema: silver
    intermediate:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold

snapshots:
  ecommerce_data_engineering:
    +schema: gold

seeds:
  ecommerce_data_engineering:
    +schema: bronze
    raw_customers:
      +column_types:
        customer_id: string
        first_name: string
        last_name: string
        email: string
        country: string
        created_at: timestamp
    raw_orders:
      +column_types:
        order_id: string
        customer_id: string
        order_date: date
        status: string
        total_amount: double
    raw_order_items:
      +column_types:
        order_item_id: string
        order_id: string
        product_id: string
        quantity: int
        unit_price: double
    raw_products:
      +column_types:
        product_id: string
        product_name: string
        category: string
        price: double
